theme: jekyll-theme-cayman



# Variaveis para caminhos de imagens 
logo: https://github.com/RonierLima/wistc-2020/blob/master/assets/images/logo.png


# Configurações internas do site
github.is_project_page: false